CREATE TABLE dbo.TestTable1
(
	MyKeyField VARCHAR(10) NOT NULL,
	TableName VARCHAR (10),
	MyDate1 DATETIME NOT NULL,
	MyDate2 DATETIME NOT NULL,
	MyDate3 DATETIME NOT NULL,
	MyDate4 DATETIME NOT NULL,
	MyDate5 DATETIME NOT NULL
)

CREATE TABLE dbo.TestTable2
(
	MyKeyField VARCHAR(10) NOT NULL,
	TableName VARCHAR (10),
	MyDate1 DATETIME NOT NULL,
	MyDate2 DATETIME NOT NULL,
	MyDate3 DATETIME NOT NULL,
	MyDate4 DATETIME NOT NULL,
	MyDate5 DATETIME NOT NULL
)